-- 为已基线的旧数据库恢复知识库面试题表。
CREATE TABLE IF NOT EXISTS knowledge_base_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR(64),
  created_at TIMESTAMP(6) NOT NULL,
  difficulty VARCHAR(16),
  follow_ups_json TEXT,
  kb_content_hash VARCHAR(64),
  key_points_json TEXT,
  knowledge_base_id BIGINT,
  question TEXT NOT NULL,
  reference_answer TEXT,
  scoring_rubric TEXT,
  skill_id VARCHAR(64) NOT NULL,
  source_context TEXT,
  status VARCHAR(20) NOT NULL,
  topic_summary VARCHAR(300),
  type VARCHAR(64),
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT knowledge_base_questions_status_check
    CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED', 'STALE')),
  CONSTRAINT fkosobqu06r3tbr13ca043slftw
    FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id)
);

CREATE INDEX IF NOT EXISTS idx_kb_question_kb_status
  ON knowledge_base_questions (knowledge_base_id, status);

CREATE INDEX IF NOT EXISTS idx_kb_question_skill_difficulty
  ON knowledge_base_questions (skill_id, difficulty);
